plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

apply plugin: 'java'

group 'org.comroid'
version '0.2.0-SNAPSHOT'

shadowJar {
    // Exclude dependencies by ensuring the JAR contains only the classes
    configurations = [project.configurations.shadow]
}

tasks.register('testPlugin', Copy) {
    dependsOn shadowJar//, dlArclightServerJar, dlPaperServerJar, dlSpigotServerJar
    from shadowJar.outputs.files.singleFile
    into "${projectDir}/run/plugins"
    rename { n -> "WorldMod-spigot.jar" }
}

task simplifyArtifact(type: Copy) {
    dependsOn test, shadowJar
    from shadowJar.outputs.files.singleFile
    into "$rootDir/build/libs/"
    rename { n -> "WorldMod-spigot.jar" }
}

repositories {
    mavenLocal()
    maven { url = 'https://maven.comroid.org' }
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    mavenCentral()
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
    if (findProject(':japi') != null)
        implementation project(':japi')
    else implementation 'org.comroid:api:1.+'
    if (findProject(':cmdr-spigot') != null)
        implementation project(':cmdr-spigot')
    else implementation 'org.comroid:cmdr-spigot:0.+'

    implementation project(':LibMod:spigot')

    compileOnly 'org.spigotmc:spigot-api:1.20-R0.1-SNAPSHOT'
    compileOnly 'org.jetbrains:annotations:23.0.0'

    // lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}
