main: de.kaleidox.jumpcube.JumpCube
name: JumpCube
version: 0.2.0-SNAPSHOT
author: Kaleidox
description: Continuation of the DeathCube plugin
api-version: 1.20
depend:
  - LibMod
softdepend:
  - WorldMod
commands:
  jumpcube:
    description: JumpCube command
    aliases:
      - jc
